version: "3.8"
services:
  web:
    restart: unless-stopped
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/workspace
    environment:
      FAST_APP: app.py
      FAST_MODE: dev # dev, prod, test 
